spring.application.name=Meeting with JWT
# JWT
jwt.secret=TXlOYW1lSXNTYXNoYUFuZElBbUFHcmVhdFByb2dyYW1tZXI=
jwt.access.expiration.ms=900000
jwt.refresh.expiration.ms=604800000
jwt.blacklist.cleanup.interval=60000